version: 2
jobs:
  test:
    docker:
      - image: node:16.10.0

    working_directory: ~/repo

    steps:
      - checkout
      - run: npm test

  build:
    docker:
      - image: node:16.10.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm i

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      #- run: npm test

      - run: npm run build

     # - run: npm run netlify:deploy
  
  deploy:
    docker:
      - image: node:16.10.0
    
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm run netlify:deploy

workflows:
  version: 2
  test-build-and-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test